### PR TITLE
Fixed the broken build caused by missing includes.

### PR DESCRIPTION
**Pull request by jieyu**
Tested on OSX 10.8.5 with jdk8 and gcc-4.8 (installed by brew).

### CODE REVIEW

**Comment by laszlocsomor** [comment]
Hi, thanks for fixing this bug! Unfortunately we cannot yet accept pull requests, only patches through Gerrit, see http://bazel.io/docs/contributing.html. Sorry for the inconvenience! We're actively working on improving this situation.

**Comment by laszlocsomor** [comment]
Sorry, I see now that you signed the CLA. Thanks!
Let me try to patch in your changes manually and make it so that you get credit for it.

**Comment by laszlocsomor** [comment]
Damien, could you please take it over while I'm away?

**Comment by damienmg** [comment]
Ok I will take care of that tomorrow afternoon

**Comment by hanwen** [comment]
fixed by https://github.com/google/bazel/commit/d52d32ef0ecfc0d784ec2fd0f1b4dcbbc03aa389

**Pull request closed without merging**
