### PR TITLE
Fixing CPU count autodetection

### PR DESCRIPTION
**Pull request by srib**
Needs some fixing as I don't have access to a Mac :-)

### CODE REVIEW

**Comment by damienmg** [comment]
A drop-by comment:
  - for non trivial contribution, we prefer to use gerrit (https://bazel-review.googlesource.com).
  - we should not have a new classes just for that (have it at least inside unix_jni).
  - you should update the Bazel build as well as compile.sh

A personal opinion: I would love to see the JNI part of Bazel disappear at some point and I don't think we should introduce more JNIsh especially when we can put the corresponding code in the client and pass flags to the server.

**Comment by hanwen** [comment]
Damien, what do you suggest?  Do you want the launcher to detect the number of CPUs and pass a --local_capacity flag instead?

**Comment by hanwen** [comment]
If we're using sysconf to get the number of CPUs, we should delete the /proc parsing as well.

**Comment by damienmg** [comment]
hanwen: Maybe if we need it to be written in C but if it is parsing the filesystem we can do it in Java. Anyway, the JNI part is probably no more needed with java.nio (this needs a lot of testing though) and I think it is better if we try not to grow it.

**Comment by hanwen** [comment]
@damienmg for linux, we want to parse the FS under /sys, under MacOS, we want to call sysctl() with "hw.ncpu" and "hw.nlogicalcpu" as arguments.

**Comment by damienmg** [comment]
then for now just adding the necessary method to unix_jni* files is probably the faster. I am sure we can call sysctl from Java with JDK 7+ but I don't find it anymore. It is just a preference anyway.

**Comment by hanwen** [comment]
According to the Java docs, getRuntime().availableProcessors()  may change according to load, so you have to poll it. I imagine it will give misleading results if we're busy dispatching lots of spawns, because it would take the load generate ourselves into account. Also, it gives the number of CPUs available to the JVM, while we may want to have what's available outside the JVM.

**Comment by hanwen** [comment]
shall we keep discussion of tentative implementation ideas on the issue itself? 

https://github.com/google/bazel/issues/101

**Pull request closed without merging**
