### PR TITLE
Allow Bazel to be distro-packaged (Part 1 of many)

### PR DESCRIPTION
**Pull request by kmoffett**
I'm working through packaging Bazel for Debian.  There are a lot of things that still need work, but these are the first few necessary changes that I was able to pop off into discrete patches.

I'm looking forward to your feedback.

Cheers,
Kyle Moffett

### CODE REVIEW

**Comment by kmoffett** [comment]
I am a Google employee, and don't need to sign a CLA.

**Comment by damienmg** [comment]
Also you might want to look at https://github.com/google/bazel/commit/a2c5425bc9ac7078d483ef63bcf575c8ef8d66b7.

I don't think we can accept the one that drops the requirements to drop the requirements of the server jar to be the first one (and the BUILD is actually fixed, there is no need for it).

**Comment by ulfjack** [comment]
Odd that googlebot doesn't handle this case. Who can we ask about that?

**Comment by hanwen** [comment]
you can fetch the repo, and then import the commit locally. The reason that it doesn't work remotely, is that stock git (as opposed to gerrit) doesn't let you fetch commits indexed by SHA1.

**Comment by kmoffett** [comment]
damienmg: Can you clarify why you can't take the one that drops the requirement to have the server jar be the first entry in the ZIP?

I'm trying to be able to build a debian-compliant packaging, and so I've got another commit to run from a pre-extracted root-owned install_base directory (EG: Files in /usr/lib/${ARCH}/bazel/_embedded_binaries).

Unfortunately, without having an actual ZIP, there is no "first entry"...

**Comment by damienmg** [comment]
More precisely I think we can but it is a bit more complicate because we
don't have the same name for the library internally and externally. That is
why I just said "I think" Maybe Ulf has more insight for that one.

If you have a commit for running a pre-extracted root, then the launcher
would change and could find the library differently in that case, can't it?

Anyway it's best to discuss those complex one over gerrit (of if you prefer
to use critique, they it's ok too + it will be faster)

**Comment by ulfjack** [comment]
We can rename it internally. However, I still don't quite follow what
you're doing, Kyle. Would you mind giving a summary of the end state you're
aiming for?

**Comment by kmoffett** [comment]
ulfjack: Basically, the installed file tree right now (after a bunch of hacky patches that aren't ready for upstream yet) looks like this:

/usr/bin/bazel (just the C++ binary, no ZIP file appended)
/usr/share/bazel/base_workspace/tools/BUILD
/usr/share/bazel/base_workspace/tools/...
/usr/lib/x86_64-linux-gnu/bazel/_embedded_binaries/libblaze-main_deploy.jar
/usr/lib/x86_64-linux-gnu/bazel/_embedded_binaries/...

With this package configuration, "bazel" just trusts the file tree under /usr/lib/x86_64-linux-gnu/bazel/ rather than trying to unpack it on every launch.

(With the hacks I made to get everything relevant to builtin rules out of //third_party, the only directory you need to symlink from the base_workspace is //tools, and there are no architecture-dependent files there.)

If file versioning _during_ package upgrades is considered a hermetic-build problem, the package version could even be included in the path, but I haven't thought super hard about whether or not I should be worried about that.

**Comment by kmoffett** [comment]
Oh, I've also been mulling over one other vague idea for how to handle cross-platform toolchains and cross-compilers on Debian.  Debian has "Multiarch" tuples, which are a slightly modified subset of GNU architecture triplets, EG: x86_64-linux-gnu/powerpc-linux-gnu/etc.

The installed compilers are all available under the corresponding "Multiarch" tuple, which is available during Debian package builds as $(DEB_BUILD_MULTIARCH) (the machine doing the build, AKA "--host_cpu" in blaze) and $(DEB_HOST_MULTIARCH). (the target machine, AKA "--cpu" in blaze)
I'm planning to use those raw triplets as the actual --host_cpu and --cpu arguments, and configure blaze's CROSSTOOL file with all of the supported compilers, etc.

Since Debian also has per-architecture JDKs that can be co-installed, I think the same strategy could work for JAVA_HOME, --java_cpu, and //tools/defaults:jdk too, but that was going to take a lot more integration work with jdk.WORKSPACE and jdk.BUILD.

**Comment by damienmg** [comment]
I don't think you need to have the jar files in the embedded directory for
that. Just symlink the jar from whatever place you are putting it to its
place in tools/jdk. + If it's pure jar file it doesn't have to live in your
x86_64 directory because it is not architecture dependent.

You don't need to tweak jdk.WORKSPACE but i think we need to make WORKSPACE
file that can be used from the package path (i.e. Package path workspace
would be cat'd instead of overwritten). I have encountered that issue from
my auto configuration prototype also.
Le ven. 24 avr. 2015 à 07:48, Kyle Moffett <notifications@github.com> a
écrit :

**Comment by ulfjack** [comment]
Instead of symlinking /usr/share/bazel/base_workspace/tools/ into your
client, we were thinking about using --package_path to overlay it onto your
client.

How are you going to setup the classpath for Bazel and how can we ensure
that the server is restarted when the jars on the classpath change (say
after a new package is installed, including dependencies)?

**Comment by kmoffett** [comment]
ulfjack: Use of --package_path seems very reasonable to me (especially if the contents of //tools are carefully placed in subdirectories so you can override one piece without having to override any others).

RE: The Bazel classpath, I hadn't actually thought about that much, but it certainly could be tricky.  Depending on exactly what should trigger a relaunch, we may also need to check the bootclasspath too.

As a first pass, at build-time I'm thinking I will symlink all loaded jar files (possibly including rt.jar) into a directory for the bazel launcher to checksum; if the checksum is different it would relaunch.  All the JAR files in Debian set "Class-Path: ..." in their manifest to reference dependencies, so limiting the classpath to ensure that unexpected dependencies don't creep in won't work without writing a custom ClassLoader.

**Comment by ulfjack** [comment]
On Sun, Apr 26, 2015 at 7:19 PM, Kyle Moffett <notifications@github.com>
wrote:

> ulfjack: Use of --package_path seems very reasonable to me (especially if
> the contents of //tools are carefully placed in subdirectories so you can
> override one piece without having to override any others).
>
> RE: The Bazel classpath, I hadn't actually thought about that much, but it
> certainly could be tricky. Depending on exactly what should trigger a
> relaunch, we may also need to check the bootclasspath too.
>
> As a first pass, at build-time I'm thinking I will symlink all loaded jar
> files (possibly including rt.jar) into a directory for the bazel launcher
> to checksum; if the checksum is different it would relaunch. All the JAR
> files in Debian set "Class-Path: ..." in their manifest to reference
> dependencies, so limiting the classpath to ensure that unexpected
> dependencies don't creep in won't work without writing a custom ClassLoader.
>

I'm not worried about the bootclasspath - we're not handling that right
now, either. I'm more worried about someone installing a new version of -
say - apache_httpclient, to fix a security issue, and it doesn't get picked
up. On second thought, as long as we cover the 'core' bazel code and make
sure to restart if that changes in the first iteration, that might be good
enough.

We don't use an extensive amount of third party code, and I was thinking
that we should move some of that out of the bazel binary itself. For
example, the maven integration could call a locally installed maven instead
of doing it in-process (and if maven isn't installed, it can still shell
out to a simple maven-compat binary that only supports simple download kind
of things). Being able to use maven code in-process is a surprising
by-product of maven being written in Java - if it was written in Python,
we'd have to call something external anyway, just as for - say - PyPI.

**Comment by damienmg** [comment]
Closing this one. Follow-up discussion should go to bazel-dev@ I think

**Pull request closed without merging**
