### PR TITLE
Testing out travis changes

### PR DESCRIPTION
**Pull request by kchodorow**
Please do not merge, I'm just using pull requests to test out the Travis CI config.

### CODE REVIEW

**Comment by damienmg** [comment]
:) so we know we don't have to handle it.

**Comment by damienmg** [comment]
Can you try to launch ./bootstrap_test.sh all instead of compile and
provide the binary generated by Bazel instead of compile sh now the
segfault should have been fixed?

**Comment by kchodorow** [comment]
Reopening.

**Comment by hanwen** [comment]
do we still need this, or can it be closed?

**Comment by damienmg** [comment]
The Travis build is still unstable so I bet they are still settings to tune.
Le mer. 15 avr. 2015 à 10:02, Han-Wen Nienhuys <notifications@github.com> a
écrit :

**Comment by kchodorow** [comment]
Yes, it's not even running bazel test yet because that consistently OOMs (bootstrap_test is "only" flaky).

**Comment by hanwen** [comment]
Can't we simply pay the travis CI folks to get a larger VM ?

**Comment by laszlocsomor** [comment]
Can I close this?

**Comment by kchodorow** [comment]
No, it still can't run `bazel test //...` without OOMing.

**Comment by damienmg** [comment]
Can we close this one? Travis seems stable now.

**Pull request closed without merging**
