### PR TITLE
Fixed a typo in Skylark docs

### PR DESCRIPTION
**Pull request by mbeards**

### CODE REVIEW

**Comment by ulfjack** [comment]
Thanks for the fix. I'm merging it, and it should show up in github later today.

**Comment by ulfjack** [comment]
Whoops. This is already fixed, but the fix isn't pushed yet.

**Comment by ulfjack** [comment]
Not fixed, I'm merging it. Sorry for the confusion.

**Comment by damienmg** [comment]
This was merged in commit 12c7f56208c2ce33fb569b352ea35de4597dbedf

**Pull request closed without merging**
